import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/nav-bar/page";
import Footer from "./components/footer/page";

/* Google Fonts */
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

/* Local Ekhaya Display Font */
const ekhayaFont = localFont({
  src: "../public/fonts/EkhayaDisplayFont.otf",
  variable: "--font-ekhaya",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Ekhaya Abattoir",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`
          antialiased
          font-sans
          ${geistSans.variable}
          ${geistMono.variable}
          ${ekhayaFont.variable}
        `}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
